/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/assets/models/fox_model.glb
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function FoxModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/assets/models/fox_model.glb');
    const { actions, names } = useAnimations(animations, group);

    useEffect(() => {
        actions[names[0]].reset().fadeIn(0.5).play();
    }, []);

    return (
        <group ref={group} position={[-15, 0, -17]} {...props} dispose={null}>
            <group name="ThirdPersonMap">
                <group
                    name="SkeletalMeshActor_UAID_5405DBFA64024D8601_2053649217_SkeletalMeshComponent0"
                    position={[9.2, 0, 15.6]}
                >
                    <skinnedMesh
                        name="SK_Fox"
                        geometry={nodes.SK_Fox.geometry}
                        material={materials.M_Fox}
                        skeleton={nodes.SK_Fox.skeleton}
                    />
                    <skinnedMesh
                        name="SK_Fox_1"
                        geometry={nodes.SK_Fox_1.geometry}
                        material={materials.M_FoxFur}
                        skeleton={nodes.SK_Fox_1.skeleton}
                    />
                    <primitive object={nodes.root} />
                </group>
            </group>
        </group>
    );
}
export default FoxModel;

useGLTF.preload('/assets/models/fox_model.glb');
