/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/assets/models/IndustrialArm/scene.gltf
Author: UX3D GmbH (https://sketchfab.com/nopper)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ux3d-industrial-robot-d8e8948191684a66a2f31c2e17e3481f
Title: UX3D Industrial Robot
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function IndustrialArm(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/assets/models/IndustrialArm/scene.gltf');
    const { actions, names } = useAnimations(animations, group);

    useEffect(() => {
        actions[names[0]].reset().fadeIn(0.5).play();
    }, []);
    return (
        <group ref={group} {...props} dispose={null} position={[20, -0.1, 0]}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="ground_3">
                                <mesh
                                    name="Object_4"
                                    geometry={nodes.Object_4.geometry}
                                    material={materials['Material.005']}
                                />
                            </group>
                            <group name="base_0">
                                <group name="rotation_arm_6" position={[0, 1.78, 0]}>
                                    <group name="joint1_4" position={[0.7, 2.68, 0.28]} rotation={[0, 0, -0.01]}>
                                        <group name="joint2_5" position={[-0.02, 6.15, -1.13]} rotation={[0, 0, 0.01]}>
                                            <group name="grab_2" position={[-12.2, 2.01, 0.74]} rotation={[0, 0, 1.57]}>
                                                <group
                                                    name="zange1_7"
                                                    position={[-3.39, 1.77, 0]}
                                                    rotation={[-Math.PI / 2, 1.43, 0]}
                                                >
                                                    <mesh
                                                        name="Object_22"
                                                        geometry={nodes.Object_22.geometry}
                                                        material={materials.aluminium}
                                                    />
                                                    <mesh
                                                        name="Object_23"
                                                        geometry={nodes.Object_23.geometry}
                                                        material={materials.black}
                                                    />
                                                </group>
                                                <group
                                                    name="zange2_8"
                                                    position={[-3.38, 0.94, 0.83]}
                                                    rotation={[-0.02, 1.44, 0.02]}
                                                >
                                                    <mesh
                                                        name="Object_25"
                                                        geometry={nodes.Object_25.geometry}
                                                        material={materials.aluminium}
                                                    />
                                                    <mesh
                                                        name="Object_26"
                                                        geometry={nodes.Object_26.geometry}
                                                        material={materials.black}
                                                    />
                                                </group>
                                                <group
                                                    name="zange3_9"
                                                    position={[-3.38, 0.11, -0.01]}
                                                    rotation={[Math.PI / 2, 1.44, 0]}
                                                >
                                                    <mesh
                                                        name="Object_28"
                                                        geometry={nodes.Object_28.geometry}
                                                        material={materials.aluminium}
                                                    />
                                                    <mesh
                                                        name="Object_29"
                                                        geometry={nodes.Object_29.geometry}
                                                        material={materials.black}
                                                    />
                                                </group>
                                                <group
                                                    name="zange4_10"
                                                    position={[-3.33, 0.95, -0.81]}
                                                    rotation={[0, 0, -1.57]}
                                                >
                                                    <mesh
                                                        name="Object_31"
                                                        geometry={nodes.Object_31.geometry}
                                                        material={materials.aluminium}
                                                    />
                                                    <mesh
                                                        name="Object_32"
                                                        geometry={nodes.Object_32.geometry}
                                                        material={materials.black}
                                                    />
                                                </group>
                                                <group
                                                    name="Empty_1"
                                                    position={[-2.98, 0.95, 0]}
                                                    rotation={[0, 0, -1.57]}
                                                />
                                                <mesh
                                                    name="Object_16"
                                                    geometry={nodes.Object_16.geometry}
                                                    material={materials.aluminium}
                                                />
                                                <mesh
                                                    name="Object_17"
                                                    geometry={nodes.Object_17.geometry}
                                                    material={materials.copper}
                                                />
                                                <mesh
                                                    name="Object_18"
                                                    geometry={nodes.Object_18.geometry}
                                                    material={materials.ivory_gripper}
                                                />
                                                <mesh
                                                    name="Object_19"
                                                    geometry={nodes.Object_19.geometry}
                                                    material={materials.grey}
                                                />
                                            </group>
                                            <mesh
                                                name="Object_14"
                                                geometry={nodes.Object_14.geometry}
                                                material={materials.ivory}
                                            />
                                        </group>
                                        <mesh
                                            name="Object_12"
                                            geometry={nodes.Object_12.geometry}
                                            material={materials['ivory_arm.001']}
                                        />
                                    </group>
                                    <mesh
                                        name="Object_10"
                                        geometry={nodes.Object_10.geometry}
                                        material={materials.grey_rotation}
                                    />
                                </group>
                                <mesh
                                    name="Object_6"
                                    geometry={nodes.Object_6.geometry}
                                    material={materials.aluminium}
                                />
                                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.black} />
                                <mesh
                                    name="Object_8"
                                    geometry={nodes.Object_8.geometry}
                                    material={materials.grey_base}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

export default IndustrialArm;

useGLTF.preload('/assets/models/IndustrialArm/scene.gltf');
