/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 .\public\assets\models\Person.gltf
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Person(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/assets/models/person.gltf');
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group>
                <group name="RootNode">
                    <primitive object={nodes.mixamorig1Hips} />
                    <skinnedMesh
                        name="Ch36"
                        geometry={nodes.Ch36.geometry}
                        material={materials.Ch36_Body}
                        skeleton={nodes.Ch36.skeleton}
                    />
                </group>
            </group>
        </group>
    );
}
export default Person;

useGLTF.preload('/assets/models/person.gltf');
