/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/assets/models/YunkRobot/scene.gltf
Author: gbaldsing (https://sketchfab.com/GBaldsing)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/junk-yard-robot-boy-1fac6302809c4f039b4e34c0cd1146b7
Title: Junk Yard Robot Boy
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useServerStore } from '../stores/ServerStore';

export function YunkRobot(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/assets/models/YunkRobot/scene.gltf');

    const { animationIndex } = useServerStore(state => ({
        animationIndex: state.animationsData.yunkAnimationData.animationIndex,
    }));

    const { actions, names } = useAnimations(animations, group);

    useEffect(() => {
        actions[names[animationIndex]].reset().fadeIn(0.5).play();
        return () => {
            actions[names[animationIndex]].fadeOut(0.5);
        };
    }, [animationIndex]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    position={[-9.13, -10.33, -0.54]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.02}
                >
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="GLTF_created_3">
                                <group name="RAMP1_96" position={[0, 0, 1.67]} scale={0}>
                                    <group name="RAMP1PIV_97" position={[0, 0, -1.67]}>
                                        <group name="RAMPShape1_98">
                                            <mesh
                                                name="Object_10"
                                                geometry={nodes.Object_10.geometry}
                                                material={materials.GLSLShader8}
                                            />
                                        </group>
                                    </group>
                                </group>
                                <primitive object={nodes.GLTF_created_3_rootJoint} />
                                <group name="CableArm_287" />
                                <group name="polySurface100_95" />
                                <group name="polySurface101_94" />
                                <group name="polySurface102_93" />
                                <group name="polySurface104_92" />
                                <group name="polySurface114_91" />
                                <group name="polySurface168_89" position={[-36.97, 27.76, 1.77]}>
                                    <group name="polySurface168PIV_90" position={[36.97, -27.76, -1.77]} />
                                </group>
                                <group name="polySurface170_87" position={[-41.24, 32.17, 1.74]}>
                                    <group name="polySurface170PIV_88" position={[41.24, -32.17, -1.74]} />
                                </group>
                                <group name="polySurface171_85" position={[-46.78, 26.49, -2]}>
                                    <group name="polySurface171PIV_86" position={[46.78, -26.49, 2]} />
                                </group>
                                <group name="polySurface173_83" position={[-42.55, 22.4, -2.14]}>
                                    <group name="polySurface173PIV_84" position={[42.55, -22.4, 2.14]} />
                                </group>
                                <group name="polySurface174_81" position={[-44.64, 24.36, -2.02]}>
                                    <group name="polySurface174PIV_82" position={[44.64, -24.36, 2.02]} />
                                </group>
                                <group name="polySurface175_79" position={[-39.17, 30.17, 1.78]}>
                                    <group name="polySurface175PIV_80" position={[39.17, -30.17, -1.78]} />
                                </group>
                                <group name="polySurface176_77" position={[-46.47, 43.96, 2.1]}>
                                    <group name="polySurface176PIV_78" position={[46.47, -43.96, -2.1]} />
                                </group>
                                <group name="polySurface177_75" position={[-42.07, 22.88, 6.85]}>
                                    <group name="polySurface177PIV_76" position={[42.07, -22.88, -6.85]} />
                                </group>
                                <group name="polySurface178_73" position={[-44.15, 24.85, 6.73]}>
                                    <group name="polySurface178PIV_74" position={[44.15, -24.85, -6.73]} />
                                </group>
                                <group name="polySurface179_71" position={[-46.28, 26.99, 6.75]}>
                                    <group name="polySurface179PIV_72" position={[46.28, -26.99, -6.75]} />
                                </group>
                                <group name="polySurface180_69" position={[31.24, 69.4, 6.08]}>
                                    <group name="polySurface180PIV_70" position={[-31.24, -69.4, -6.08]} />
                                </group>
                                <group name="polySurface181_67" position={[23.24, 74.03, 6.08]}>
                                    <group name="polySurface181PIV_68" position={[-23.24, -74.03, -6.08]} />
                                </group>
                                <group name="polySurface186_65" position={[59.63, 37.62, 12.8]}>
                                    <group name="polySurface186PIV_66" position={[-59.63, -37.62, -12.8]} />
                                </group>
                                <group name="polySurface187_63" position={[61.43, 35.81, 15.79]}>
                                    <group name="polySurface187PIV_64" position={[-61.43, -35.81, -15.79]} />
                                </group>
                                <group name="polySurface188_61" position={[59.99, 40.14, 6.38]}>
                                    <group name="polySurface188PIV_62" position={[-59.99, -40.14, -6.38]} />
                                </group>
                                <group name="polySurface190_59" position={[65.97, 36.2, 8.1]}>
                                    <group name="polySurface190PIV_60" position={[-65.97, -36.2, -8.1]} />
                                </group>
                                <group name="polySurface191_57" position={[65.97, 36.2, 2.83]}>
                                    <group name="polySurface191PIV_58" position={[-65.97, -36.2, -2.83]} />
                                </group>
                                <group name="polySurface194_55" position={[69.62, 32.55, 8.07]}>
                                    <group name="polySurface194PIV_56" position={[-69.62, -32.55, -8.07]} />
                                </group>
                                <group name="polySurface195_53" position={[69.62, 32.55, 2.86]}>
                                    <group name="polySurface195PIV_54" position={[-69.62, -32.55, -2.86]} />
                                </group>
                                <group name="polySurface196_51" position={[72.18, 29.94, 8.11]}>
                                    <group name="polySurface196PIV_52" position={[-72.18, -29.94, -8.11]} />
                                </group>
                                <group name="polySurface197_49" position={[72.18, 29.94, 2.83]}>
                                    <group name="polySurface197PIV_50" position={[-72.18, -29.94, -2.83]} />
                                </group>
                                <group name="polySurface198_48" />
                                <group name="polySurface199_47" />
                                <group name="polySurface200_46" />
                                <group name="polySurface201_45" />
                                <group name="polySurface210_44" />
                                <group name="polySurface235_43" />
                                <group name="polySurface238_42" />
                                <group name="polySurface254_40" position={[9.68, 44.83, -0.31]}>
                                    <group name="polySurface254PIV_41" position={[-9.68, -44.83, 0.31]} />
                                </group>
                                <group name="polySurface255_38" position={[12.46, 41.58, -0.31]}>
                                    <group name="polySurface255PIV_39" position={[-12.46, -41.58, 0.31]} />
                                </group>
                                <group name="polySurface256_36" position={[12.59, 17.23, -2.82]}>
                                    <group name="polySurface256PIV_37" position={[-12.59, -17.23, 2.82]} />
                                </group>
                                <group name="polySurface258_34" position={[12.47, 3.68, 5.26]}>
                                    <group name="polySurface258PIV_35" position={[-12.47, -3.68, -5.26]} />
                                </group>
                                <group name="polySurface259_32" position={[12.14, 4.16, -1.89]}>
                                    <group name="polySurface259PIV_33" position={[-12.14, -4.16, 1.89]} />
                                </group>
                                <group name="polySurface260_30" position={[12.11, 6.72, -3.55]}>
                                    <group name="polySurface260PIV_31" position={[-12.11, -6.72, 3.55]} />
                                </group>
                                <group name="polySurface262_28" position={[0, 46.28, -0.31]}>
                                    <group name="polySurface262PIV_29" position={[0, -46.28, 0.31]} />
                                </group>
                                <group name="polySurface263_26" position={[-11.79, 36.04, 1.03]}>
                                    <group name="polySurface263PIV_27" position={[11.79, -36.04, -1.03]} />
                                </group>
                                <group name="polySurface264_24" position={[-11.92, 18.25, 4.4]}>
                                    <group name="polySurface264PIV_25" position={[11.92, -18.25, -4.4]} />
                                </group>
                                <group name="polySurface265_22" position={[-12.02, 5.7, 6.61]}>
                                    <group name="polySurface265PIV_23" position={[12.02, -5.7, -6.61]} />
                                </group>
                                <group name="polySurface266_20" position={[50.33, 50.71, 5.6]}>
                                    <group name="polySurface266PIV_21" position={[-50.33, -50.71, -5.6]} />
                                </group>
                                <group name="polySurface267_18" position={[-26.91, 76.57, 2]}>
                                    <group name="polySurface267PIV_19" position={[26.91, -76.57, -2]} />
                                </group>
                                <group name="polySurface268_16" position={[-3.24, 68.34, 3.67]}>
                                    <group name="polySurface268PIV_17" position={[3.24, -68.34, -3.67]} />
                                </group>
                                <group name="polySurface2_15" />
                                <group name="polySurface47_13" position={[-3.24, 68.34, 3.67]}>
                                    <group name="polySurface47PIV_14" position={[3.24, -68.34, -3.67]} />
                                </group>
                                <group name="polySurface49_11" position={[-7.66, 75.01, -13.09]}>
                                    <group name="polySurface49PIV_12" position={[7.66, -75.01, 13.09]} />
                                </group>
                                <group name="polySurface50_9" position={[0.66, 114.33, -0.03]}>
                                    <group name="polySurface50PIV_10" position={[-0.66, -114.33, 0.03]} />
                                </group>
                                <group name="polySurface51_7" position={[-24.26, 112.06, 27.63]}>
                                    <group name="polySurface51PIV_8" position={[24.26, -112.06, -27.63]} />
                                </group>
                                <group name="polySurface52_5" position={[0.73, 97.71, 0.95]}>
                                    <group name="polySurface52PIV_6" position={[-0.73, -97.71, -0.95]} />
                                </group>
                                <group name="polySurface53_3" position={[-7.65, 61.42, -13.94]}>
                                    <group name="polySurface53PIV_4" position={[7.65, -61.42, 13.94]} />
                                </group>
                                <group name="polySurface88_2" />
                                <group name="polySurface89_1" />
                                <group name="polySurface98_0" />
                                <skinnedMesh
                                    name="Object_6"
                                    geometry={nodes.Object_6.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_6.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_12"
                                    geometry={nodes.Object_12.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_12.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_14"
                                    geometry={nodes.Object_14.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_14.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_16"
                                    geometry={nodes.Object_16.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_16.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_18"
                                    geometry={nodes.Object_18.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_18.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_20"
                                    geometry={nodes.Object_20.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_20.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_23"
                                    geometry={nodes.Object_23.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_23.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_26"
                                    geometry={nodes.Object_26.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_26.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_27"
                                    geometry={nodes.Object_27.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_27.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_30"
                                    geometry={nodes.Object_30.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_30.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_31"
                                    geometry={nodes.Object_31.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_31.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_34"
                                    geometry={nodes.Object_34.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_34.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_37"
                                    geometry={nodes.Object_37.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_37.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_40"
                                    geometry={nodes.Object_40.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_40.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_43"
                                    geometry={nodes.Object_43.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_43.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_46"
                                    geometry={nodes.Object_46.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_46.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_49"
                                    geometry={nodes.Object_49.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_49.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_52"
                                    geometry={nodes.Object_52.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_52.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_53"
                                    geometry={nodes.Object_53.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_53.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_56"
                                    geometry={nodes.Object_56.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_56.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_59"
                                    geometry={nodes.Object_59.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_59.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_62"
                                    geometry={nodes.Object_62.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_62.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_65"
                                    geometry={nodes.Object_65.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_65.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_68"
                                    geometry={nodes.Object_68.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_68.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_71"
                                    geometry={nodes.Object_71.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_71.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_74"
                                    geometry={nodes.Object_74.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_74.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_77"
                                    geometry={nodes.Object_77.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_77.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_80"
                                    geometry={nodes.Object_80.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_80.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_83"
                                    geometry={nodes.Object_83.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_83.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_86"
                                    geometry={nodes.Object_86.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_86.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_88"
                                    geometry={nodes.Object_88.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_88.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_90"
                                    geometry={nodes.Object_90.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_90.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_92"
                                    geometry={nodes.Object_92.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_92.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_94"
                                    geometry={nodes.Object_94.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_94.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_96"
                                    geometry={nodes.Object_96.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_96.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_98"
                                    geometry={nodes.Object_98.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_98.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_100"
                                    geometry={nodes.Object_100.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_100.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_103"
                                    geometry={nodes.Object_103.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_103.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_106"
                                    geometry={nodes.Object_106.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_106.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_109"
                                    geometry={nodes.Object_109.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_109.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_112"
                                    geometry={nodes.Object_112.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_112.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_115"
                                    geometry={nodes.Object_115.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_115.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_118"
                                    geometry={nodes.Object_118.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_118.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_121"
                                    geometry={nodes.Object_121.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_121.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_124"
                                    geometry={nodes.Object_124.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_124.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_127"
                                    geometry={nodes.Object_127.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_127.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_130"
                                    geometry={nodes.Object_130.geometry}
                                    material={materials.lowerShader}
                                    skeleton={nodes.Object_130.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_133"
                                    geometry={nodes.Object_133.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_133.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_136"
                                    geometry={nodes.Object_136.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_136.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_139"
                                    geometry={nodes.Object_139.geometry}
                                    material={materials.TapeCTRLS}
                                    skeleton={nodes.Object_139.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_141"
                                    geometry={nodes.Object_141.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_141.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_144"
                                    geometry={nodes.Object_144.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_144.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_145"
                                    geometry={nodes.Object_145.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_145.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_146"
                                    geometry={nodes.Object_146.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_146.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_149"
                                    geometry={nodes.Object_149.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_149.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_152"
                                    geometry={nodes.Object_152.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_152.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_155"
                                    geometry={nodes.Object_155.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_155.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_158"
                                    geometry={nodes.Object_158.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_158.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_161"
                                    geometry={nodes.Object_161.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_161.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_162"
                                    geometry={nodes.Object_162.geometry}
                                    material={materials.UpperBody}
                                    skeleton={nodes.Object_162.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_164"
                                    geometry={nodes.Object_164.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_164.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_166"
                                    geometry={nodes.Object_166.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_166.skeleton}
                                />
                                <skinnedMesh
                                    name="Object_168"
                                    geometry={nodes.Object_168.geometry}
                                    material={materials.ArmsShader}
                                    skeleton={nodes.Object_168.skeleton}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

export default YunkRobot;

useGLTF.preload('/assets/models/YunkRobot/scene.gltf');
